--TABLE CREATION
CREATE TABLE BEAR (
    BEAR_ID INTEGER PRIMARY KEY,
    BEAR_NAME VARCHAR2(100),
    BEAR_BIRTHDATE DATE,
    BEAR_WEIGHT NUMBER(5,2) DEFAULT 200.00,
    BEAR_TYPE_ID INTEGER NOT NULL,
    CAVE_ID INTEGER
);
/
CREATE TABLE BEAR_TYPE (
    BEAR_TYPE_ID INTEGER PRIMARY KEY,
    BEAR_TYPE_NAME VARCHAR2(100)
);
/
CREATE TABLE CAVE (
    CAVE_ID INTEGER PRIMARY KEY,
    CAVE_NAME VARCHAR2(100),
    MAX_BEARS INTEGER DEFAULT 4
);
/
CREATE TABLE BEEHIVE (
    BEEHIVE_ID INTEGER PRIMARY KEY,
    BEEHIVE_NAME VARCHAR2(100),
    WEIGHT NUMBER(5,2) DEFAULT 75.00
);
/
CREATE TABLE BEAR_BEEHIVE (
    BEAR_ID INTEGER,
    BEEHIVE_ID INTEGER,
    PRIMARY KEY (BEAR_ID, BEEHIVE_ID)
);
/

--FORIEGN KEY CONSTRAINTS 
ALTER TABLE BEAR
ADD CONSTRAINT FK_BEAR_BEAR_TYPE
FOREIGN KEY (BEAR_TYPE_ID) REFERENCES BEAR_TYPE(BEAR_TYPE_ID);
/
ALTER TABLE BEAR
ADD CONSTRAINT FK_BEAR_CAVE
FOREIGN KEY (CAVE_ID) REFERENCES CAVE(CAVE_ID);
/
ALTER TABLE BEAR_BEEHIVE
ADD CONSTRAINT FK_BEAR_BEAR_BEEHIVE
FOREIGN KEY (BEAR_ID) REFERENCES BEAR(BEAR_ID);
/
ALTER TABLE BEAR_BEEHIVE
ADD CONSTRAINT FK_BEEHIVE_BEAR_BEEHIVE
FOREIGN KEY (BEEHIVE_ID) REFERENCES BEEHIVE(BEEHIVE_ID);
/

--ADD SOME DATA

INSERT INTO BEAR_TYPE VALUES (1,'Grizzly');
INSERT INTO BEAR_TYPE(BEAR_TYPE_ID,BEAR_TYPE_NAME) VALUES (2,'Sun');

INSERT ALL
INTO CAVE 
VALUES (1,'AWESOMECAVE1',9)
INTO CAVE(CAVE_ID,CAVE_NAME)
VALUES (2, 'Queens')
SELECT * FROM DUAL; --DUAL IS A DUMMY TABLE 

INSERT ALL
INTO BEAR(BEAR_ID, BEAR_NAME, BEAR_BIRTHDATE, BEAR_TYPE_ID, CAVE_ID)
VALUES (3,'Ursula',TO_DATE('1980-08-08 00:00:00','yyyy-mm-dd hh24:mi:ss'), 1, 2)
INTO BEAR(BEAR_ID, BEAR_NAME, BEAR_BIRTHDATE, BEAR_TYPE_ID, CAVE_ID)
VALUES (5,'Truckski',TO_DATE('1999-08-08 00:00:00','yyyy-mm-dd hh24:mi:ss'), 2, 2)
INTO BEAR
VALUES (8,'Maleficent',TO_DATE('1980-08-08 00:00:00','yyyy-mm-dd hh24:mi:ss'), 400.00, 1, 1)
SELECT * FROM DUAL;

--THIS DOES NOT WORK
--INSERT INTO BEAR(BEAR_ID, BEAR_NAME, BEAR_BIRTHDATE, BEAR_TYPE_ID, CAVE_ID)
--VALUES (9,'Ferdinand',TO_DATE('1980-08-08 00:00:00','yyyy-mm-dd hh24:mi:ss'), 1, 10);