
package com.revature.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlashcardServiceImplService", targetNamespace = "http://soap.revature.com/", wsdlLocation = "http://localhost:8084/SoapServiceDemo/Flashcard?wsdl")
public class FlashcardServiceImplService
    extends Service
{

    private final static URL FLASHCARDSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FLASHCARDSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FLASHCARDSERVICEIMPLSERVICE_QNAME = new QName("http://soap.revature.com/", "FlashcardServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/SoapServiceDemo/Flashcard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLASHCARDSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FLASHCARDSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FlashcardServiceImplService() {
        super(__getWsdlLocation(), FLASHCARDSERVICEIMPLSERVICE_QNAME);
    }

    public FlashcardServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLASHCARDSERVICEIMPLSERVICE_QNAME, features);
    }

    public FlashcardServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, FLASHCARDSERVICEIMPLSERVICE_QNAME);
    }

    public FlashcardServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLASHCARDSERVICEIMPLSERVICE_QNAME, features);
    }

    public FlashcardServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlashcardServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlashcardService
     */
    @WebEndpoint(name = "FlashcardServiceImplPort")
    public FlashcardService getFlashcardServiceImplPort() {
        return super.getPort(new QName("http://soap.revature.com/", "FlashcardServiceImplPort"), FlashcardService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlashcardService
     */
    @WebEndpoint(name = "FlashcardServiceImplPort")
    public FlashcardService getFlashcardServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.revature.com/", "FlashcardServiceImplPort"), FlashcardService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLASHCARDSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FLASHCARDSERVICEIMPLSERVICE_EXCEPTION;
        }
        return FLASHCARDSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
